$('#filter_samples_title').html(chrome.i18n.getMessage("filter_samples_title"));
$('#no_filter_sample_title').html(chrome.i18n.getMessage("no_filter_sample_title"));
$('#all_filter_sample_title').html(chrome.i18n.getMessage("all_filter_sample_title"));
$('#custom_filter_sample_title').html(chrome.i18n.getMessage("custom_filter_sample_title"));
$('#filter_sample_intro').html(chrome.i18n.getMessage("filter_sample_intro"));
$('#filter_sample_example').html(chrome.i18n.getMessage("filter_sample_example"));
$('#filter_sample_example_1').html(chrome.i18n.getMessage("filter_sample_example"));
$('#filter_sample_example_2').html(chrome.i18n.getMessage("filter_sample_example"));
$('#no_filter_ignore_checked').html(chrome.i18n.getMessage("no_filter_ignore_checked"));
$('#no_filter_ignore_unchecked').html(chrome.i18n.getMessage("no_filter_ignore_unchecked"));
$('#filter_sample_all').html(chrome.i18n.getMessage("filter_sample_all"));
$('#filter_sample_custom').html(chrome.i18n.getMessage("filter_sample_custom"));
$('#youtube_link').attr("title", chrome.i18n.getMessage("youtube_link_text"));